### ISSUE TITLE
No instance for `(MonadReader () (State () IO))`

### ISSUE THREAD

**Issue by crockeea** [strake/monad-classes.hs#4]
The following code fails to compile with GHC 8.6.3 and monad-classes-0.3.2.2 (with everything else from Stack LTS-13.2):

```
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies     #-}

import Control.Monad.Classes (MonadReader)
--import Control.Monad.Primitive ()
import Control.Monad.Trans.State.Lazy (StateT)

main :: (n ~ StateT () IO, MonadReader () n) => IO ()
main = undefined
```

with the error 

```
Main.hs:9:1: error:
        * No instance for (monad-classes-0.3.2.2:Control.Monad.Classes.Reader.MonadReaderN
                             (monad-classes-0.3.2.2:Control.Monad.Classes.Core.FindTrue
                                '[monad-classes-0.3.2.2:Control.Monad.Classes.Core.CanDo
                                    (StateT () IO)
                                    (monad-classes-0.3.2.2:Control.Monad.Classes.Effects.EffReader ()),
                                  monad-classes-0.3.2.2:Control.Monad.Classes.Core.CanDo
                                    IO
                                    (monad-classes-0.3.2.2:Control.Monad.Classes.Effects.EffReader
                                       ())])
                             ()
                             (StateT () IO))
            arising from a use of `main'
        * In the expression: main
          When checking the type of the IO action `main'
      |
    9 | main = undefined
      | ^
```

But when I uncomment the import for `Control.Monad.Primitive`, it compiles without complaint. It's unclear if this is a GHC bug or a problem with this package. My intuition is the former, but I thought someone here might have a different explanation.

**Comment by crockeea** [comment]
Possibly related: [#16211](https://ghc.haskell.org/trac/ghc/ticket/16211)

**Comment by strake** [comment]
I can reproduce. It seems it's GHC's fault — i can build it with an explicit module header:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies     #-}

module Main where

import Control.Monad.Classes (MonadReader)
--import Control.Monad.Primitive ()
import Control.Monad.Trans.State.Lazy (StateT)

main :: (n ~ StateT () IO, MonadReader () n) => IO ()
main = undefined
```

Can you confirm?

**Comment by crockeea** [comment]
I can reproduce with an explicit module header, though I'm not sure why you mention it; is it relevant? 

I was hoping to remove the dependence on monad-classes if this is indeed a GHC bug, but was unable to do so after considerable effort. Any ideas about what instances from Control.Monad.Primitive would make this compile?

**Comment by strake** [comment]
Whether the file has an explicit module header indeed ought to be irrelevant, but for me affects whether GHC builds the module or fails with the aforesaid error. And monad-classes has no transitive dependency on primitve. I'm puzzled at this point and will need to investigate further. Can you merely import `Control.Monad.Primitive` for now, as in your example?

**Comment by crockeea** [comment]
Ah, so you are saying that *without* the module header, the program compiles successfully? This is indeed interesting... Are you using stack or cabal?

**Comment by strake** [comment]
No, the opposite — it works **with** the header. I'm using stack and tried LTS-12.0 and LTS-13.2.

**Comment by crockeea** [comment]
Okay, upon reading your initial comment again, I see what you meant. 

Interestingly, I get the error with or without the explicit module header. I'm also using LTS-13.2 with an extra-deps of monad-classes-0.3.2.2.

**Comment by strake** [comment]
Ah, i can reproduce with an explicit module header if i'm building an **executable** rather than a **library**.

**Comment by strake** [comment]
What's even more puzzling, the following works for me:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies     #-}

import Control.Monad.Classes (MonadReader)
--import Control.Monad.Primitive ()
import Control.Monad.Trans.State.Lazy (StateT)

main :: IO ()
main = pure ()

blah :: (MonadReader () (StateT () IO)) => ()
blah = ()
```

**Comment by crockeea** [comment]
Ah, I see the confusion. I didn't include the cabal file, which does indeed compile this as an executable. Another clue.

I also noticed that the bug required the type synonym. Not clear what that means. If you don't see a way to reduce, I guess I'll file a GHC bug as-is.

**Comment by crockeea** [comment]
Closing in favor of https://ghc.haskell.org/trac/ghc/ticket/16234.
